### ISSUE TITLE
0.8.10 build

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/httpretty-feedstock#3]
I'm trying to get a conda build of [`moto`](https://github.com/spulec/moto) together, and it depends on `httpretty==0.8.10`. Can we temporarily get a build of the old version together so that the build works? I can make a pull request...

**Comment by ocefpaf** [comment]
Sure we can and I guess that #4 would do the job. I closed that one due to inactivity but let me know if we need to re-open it.
